<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="3.285" tests="7" failures="1">
  <testsuite name="Root Suite" timestamp="2021-01-27T21:33:30" tests="0" file="cypress\integration\covid-tests\network_requests.spec.js" failures="0" time="0">
  </testsuite>
  <testsuite name="Network Requests" timestamp="2021-01-27T21:33:30" tests="7" failures="1" time="3.285">
    <testcase name="Network Requests cy.server() - control behavior of network requests and responses" time="0.458" classname="cy.server() - control behavior of network requests and responses">
    </testcase>
    <testcase name="Network Requests cy.request() - make an XHR request" time="0.662" classname="cy.request() - make an XHR request">
    </testcase>
    <testcase name="Network Requests cy.request() - verify response using BDD syntax" time="0.505" classname="cy.request() - verify response using BDD syntax">
    </testcase>
    <testcase name="Network Requests cy.request() with query parameters" time="0.511" classname="cy.request() with query parameters">
    </testcase>
    <testcase name="Network Requests cy.request() - pass result to the second request" time="0.553" classname="cy.request() - pass result to the second request">
    </testcase>
    <testcase name="Network Requests cy.request() - save response in the shared test context" time="0.596" classname="cy.request() - save response in the shared test context">
    </testcase>
    <testcase name="Network Requests cy.route() - route responses to matching requests" time="0" classname="cy.route() - route responses to matching requests">
      <failure message="expected { Object (name, email, ...) } to have property &apos;name&apos; of &apos;Using POST in cy.route()&apos;, but got &apos;Using POST in cy.intercept()&apos;" type="AssertionError"><![CDATA[AssertionError: expected { Object (name, email, ...) } to have property 'name' of 'Using POST in cy.route()', but got 'Using POST in cy.intercept()'
    at Context.eval (https://example.cypress.io/__cypress/tests?p=cypress\integration\covid-tests\network_requests.spec.js:247:40)]]></failure>
    </testcase>
  </testsuite>
</testsuites>